# Site
repository: hbaudry/hbaudry.github.io
favicon: images/favicon.ico

# Personal info
name: Herve Baudry
title: Cybersecurity consultant
email: herve.baudry@gmail.com
website: hbaudry.github.io

# Social links
twitter_username: baudryherve
github_username:  hbaudry
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: hervebaudry
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
about_title: About Me
# about_profile_image: images/profile.jpg
# about_content: | # Hi, my name's Herve I am specialized in IS Security Governance, with a background of licensed Compliance officer and Permanent Control on Financial market. I have developped skills in IT risk, IS Security standards compliance and project management and BCP/DRP.I am most skilled in: <mark>ISO/IEC 27001</mark> <mark> ISO/IEC 27005</mark> <mark>ISO/IEC 22301</mark> <mark> SWIFT CSP</mark> <mark>EBA ICT Regulation</mark> and <mark>PCI DSS</mark>

# Projects Section
# projects_title: Projects

# Experience Section
experience_title: Experience

# Certification Section
educaton_title: Certifications
  Test de certifcations
    - Certification 1
    - Certtification 2

# Education Section
educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
